#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap          25
bspc config split_ratio         0.7
bspc config click_to_focus   true
bspc config presel_feedback_color \#3db8d3

bspc monitor eDP1 -d I II III IV V VI VII VIII IX
bspc monitor DP1 -d I II III IV V VI VII VIII IX
bspc monitor DP2 -d I II III IV V VI VII VIII IX
