#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap          25
bspc config split_ratio         0.7
bspc config click_to_focus   true
bspc config presel_feedback_color \#3db8d3

source ~/.config/extra-bspwm-config.sh
