#! /bin/sh

bspc config border_width        1
bspc config window_gap         0

#bspc config split_ratio         0.52
#bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc config auto_cancel true

bspc monitor DP-0 -d I II III IV V VI VII VIII IX
