#! /bin/sh

bspc config border_width        2
bspc config window_gap         2

#bspc config split_ratio         0.52
#bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc config auto_cancel true

bspc monitor DP1 -d I II III
bspc monitor DP2 -d I II III
bspc monitor eDP1 -d I II III
