#! /bin/sh

bspc config border_width        2
bspc config window_gap          25
bspc config split_ratio         0.7
bspc config click_to_focus   true
bspc config presel_feedback_color \#3db8d3

bspc monitor DP-0 -d I II III IV V VI VII VIII IX
